### ISSUE TITLE
Cant open Second Window three times with Titanium 3.5.0 SDK

### ISSUE THREAD

**Issue by max1020** [ricardoalcocer/AlloyAppTemplate#1]
Hello Ricardo,

Thanks for this great and really useful contribution! 

There is an issue with Titanium 3.5.0 Titanium SDK (works perfectly with SDK 3.4.1)

In 3.5.0 Titanium SDK im starting a fresh project (the Ricardo Bootstrap template) and after running it in ios 8.1 simulator (i tried iPhone 4S, 5 and 6, same result) i can only open (and close) the secondwin only twice. When i click the "plus" button a third time, nothing happens and it does not open the secondwin.

**Comment by kneibdev** [comment]
Same problem here...

**Comment by ricardoalcocer** [comment]
This is so odd.  It looks like a bug on the SDK.  I'll file a ticket and will add the ticket number here for everyone to track.

**Comment by ricardoalcocer** [comment]
Here's the ticket number: https://jira.appcelerator.org/browse/TIMOB-18663

**Comment by kneibdev** [comment]
Thanks!

**Comment by ricardoalcocer** [comment]
I was able to dig up a little more and the problem is caused by this:

https://github.com/ricardoalcocer/AlloyAppTemplate/blob/master/app/views/ios/home.xml#L14

There was a bug on RightNavButtons, which is already solved and should be available in the next version of the SDK.  As a workaround, use <RightNavButton> instead.

R
